- personality/se_dpm/config.pan
> DPM config: ensure that the DPM-readable version of host certificate is created

- repository/config/grid.pan
* Define by default WLCG repository accordingly to OS_VERSION_PARAMS['major'] value
* Makes WLCG repository name definable
* Fixes #118
> Change the method how the WLCG repo name is defined

- personality/lb/config.pan
- personality/lb/messaging.pan
- personality/lb/service.pan
- personality/wms/config.pan
- personality/wms/job-wrapper.pan
- personality/wms/service.pan
No functional change.
Tested with examples. Ready for insertion into 15.4 release (https://github.com/quattor/release/issues/92).
> WMS and LB: use new (simpler) include syntax

- features/blparser/config.pan
- features/htcondor/client/service.pan
- features/htcondor/config.pan
- features/htcondor/params.pan
- features/htcondor/server/groups.pan
- features/htcondor/server/service.pan
- features/htcondor/templ/groups.pan
- features/htcondor/templ/head.pan
- features/htcondor/templ/preempt.pan
- features/htcondor/templ/submit.pan
- features/htcondor/templ/worker.pan
Some additionnal modification to integrate HTCondor into CREAM-CE
> umd-3.htcondor

- features/wlcg/config.pan
- personality/ui/rpms/config.pan
- personality/ui/service.pan
- personality/wn/rpms/config.pan
- personality/wn/service.pan
> Move WLCG related stuff in features/wlcg

- features/wlcg/config.pan
We really need unit tests for the template library!
> HEP OSLibs: fix package list cleared when HEP_OSLIBS=false

- personality/argus/pep.pan
As it is, the current template is completely broken...
> ARGUS: fix service to restart after a sysconfig file change

- repository/config/grid.pan
Because of a typo, explicit definition ignored previously.
> YUM repo: fix definition of YUM_EMI_SNAPSHOT_DATE

- features/htcondor/templ/worker-default
- features/htcondor/templ/worker.pan
Just a small change in the way draining and offline nodes are managed. In prod at GRIF_LLR
> new offline/draining mechanism for condor nodes

- features/gip/ce-maui-plugin-defaults.pan
> GIP_CE_MAUI_PLUGIN_DEFAULTS_FILE should be world readable

- features/htcondor/client/worker.pan
- features/htcondor/config.pan
- features/htcondor/params.pan
- features/htcondor/templ/condor_mic_discovery.pan
- features/htcondor/templ/gpu.pan
- features/htcondor/templ/mic.pan
Minimal setup for supporting gpu and intel mic resources. Tested with grid submission with Marco Verlato and Lisa Zangrando.
> support for gpu and intel mic resources

- features/torque2/client/job-features.pan
- personality/wn/machine-features.pan
Updated to comply with the new [specification](https://twiki.cern.ch/twiki/bin/view/LCG/MachineJobFeaturesSpec).
> Worker Node: update 'machine/job features' to current specification

- features/lcas/base.pan
- replace "nlist" with "dict"
- allow for not enabling LCAS's timeslots plugin
> Make LCAS' timeslots plugin optional

- defaults/grid/config.pan
- features/torque2/client/config.pan
Allows hyperthreading parameter to be removed later.
Includes some extra tidying up while I was touching things including fixing bugs exposed by panc 10.3.
> Use CPU max_threads to calculate slot count

- .travis-scripts/panlint
- .travis.yml
Same as for template-library-core.
> Configure travis to run linting tests

- personality/cream_ce/monitor.pan
This commit fix two issues:
* Fix cream ce monitor config file location
* Fix panlint errors
> Fix the CREAM CE Monitor configuration file path

- repository/config/htcondor.pan
> repository/config/htcondor: Cleanup and make use of repository name

- personality/wn/machine-features.pan
- personality/wn/templ/mjf.init
The changes are based on https://gitlab.cern.ch/machinejobfeatures/mjf-scripts.
Fix #155
> Machine job feature bug fix

- personality/se_dpm/puppet/puppetconf.pan
- personality/se_dpm/rpms/config.pan
- personality/se_dpm/service_puppet.pan
upstreaming some changes in the templates related to the ncm-puppet configuration of dpm which are running in production at GRIF.
> umd-4 dpm puppet templates in production at grif

- features/wlcg/config.pan
These were part of #196 for umd-3.
> umd-4: Backport cleanup from umd-3 branch

- personality/ui_gsissh/config.pan
> Ensure GSISSH_PORT is a string

- features/mariadb/server.pan
- features/mysql/server.pan
- features/puppet/defaults.pan
- features/puppet/defaults_6+.pan
- personality/cream_ce/service.pan
- personality/se_dpm/puppet/mysql.pan
- personality/se_dpm/puppet/release_modules.pan
- personality/se_dpm/rpms/config.pan
- personality/se_dpm/rpms/dav.pan
- personality/se_dpm/server/service.pan
- personality/se_dpm/service_puppet.pan
This PR contains several fixes that permit to fix the usage of ncm-puppet with Puppet v6 and the last release of DPM.
> Puppet cleanup

- .ci-scripts/indent
- .ci-scripts/panlint
- .ci-scripts/test-library
- .github/workflows/continuous-integration.yaml
I was afraid that this PR could not be tested before merging it but it seems the new CI config has been executed...
> Modernize CI scripts
