quattor/template-library-grid

features/gip/wms.pan

With the previous code, GlueServiceStatus and GlueServiceVersion were published with wrong values ('Other' and 4.4.4.4). The fix permits to publish correct values (see http://gstat2.grid.sinica.edu.tw/gstat/ldap/browse?host=ldap://sbgbdii1.in2p3.fr:2170/&entry=true&dn=glueserviceuniqueid=sbgwms1.in2p3.fr_org.glite.wms.WMProxy,mds-vo-name=IN2P3-IRES,o=grid).

Fix WMProxy status and rpm version checks

---

features/gip/lb.pan

With the previous code, GlueServiceStatus and GlueServiceVersion were published with wrong values ('Other' and 4.4.4.4). The fix permits to publish correct values (see http://gstat2.grid.sinica.edu.tw/gstat/ldap/browse?host=ldap://sbgbdii1.in2p3.fr:2170/&entry=true&dn=glueserviceuniqueid=sbgwms1.in2p3.fr_org.glite.lb.server,mds-vo-name=IN2P3-IRES,o=grid).

Fix LBSERVER status and rpm version checks

---

personality/wn/config.pan
personality/wn/machine-features.pan

Machine features permit to define WN specific parameters, like HS06 value or shutdown time:
https://twiki.cern.ch/twiki/bin/view/LCG/MachineJobFeatures

Add machine features to wn.

---

features/torque2/server/config.pan

With the version torque 2.5.13-1cri.9nik.el6 the configuration directory is /var/spool/pbs, which differs from /var/torque. Use the TORQUE_CONFIG_DIR variable to place the myinit.sh script.

Use the TORQUE_CONFIG_DIR variable to place the myinit.sh script

---

personality/argus/pep.pan

These changes are necessary for the [suggested workarounds] (https://twiki.cern.ch/twiki/bin/view/EGEE/ArgusEMIDeployment).

Argus: allow workarounds for performance issues

---

features/gip/ce.pan

fix pbs static ldif paths when GIP_CE_USE_CACHE is true

---

features/nfs/client/autofs.pan

Uses SL6+ syntax (probably not working on SL5 and before).
Fixes #101.

NFS client: fix definition of NFS version to use (autofs)

---

features/gip/ce-maui-plugin-defaults.pan

It fixes the bug https://github.com/quattor/template-library-grid/issues/148

The /etc/lrms/lcg-info-dynamic-maui.defaults file should be readable by any

---

features/torque2/server/config.pan

This fixes an error I introduced a long ago, in the svn times. I was fooled by wns with hyperthreading activated.
This bug affected filtering of parallel jobs. It also prevents someone to use variable `WN_CPU_SLOTS` as a nlist.

fix nlist WN_CPU_SLOTS

---

personality/se_dpm/puppet/puppetconf.pan
personality/se_dpm/rpms/config.pan

Some fixes for making the DPM configuration via ncm-puppet compatible with the last versions of modules (this is the configuration running at GRIF since quite a while)

conf for new puppet modules

---

defaults/grid/config.pan
features/gip/ce.pan
features/maui/server/config.pan
features/torque2/server/config.pan

Hi,
added #slots on top of #cores in WN_CPU_CONFIG & CE_CPU_CONFIG, for cases of CPUs with hyperthreading. So the information of the number of physical & logical cores(= # slots) are both present. Reporting is done on #slots, which is by default the same as #cores if boolean hyperthreading is not set in any /hardware/cpu.
Behaviour should not change for sites as long as they don't set hyperthreading to true.
Cheers
Romain

Slot reporting

---

features/torque2/client/config.pan
features/torque2/client/job-features.pan
personality/wn/machine-features.pan

Here is a draft for the documentation for these features:
To activate it you must set the following:
```
variable WN_MACHINE_FEATURES_ENABLED ?= 'true';
```
The information to be written out to the different files must be added to Quattor, by using one (or a combination of) the following two methods:
1. by defining the following variables for the worker nodes :
```
NODE_HEP_SPEC06
NODE_SHUTDOWN_TIME
NODE_JOB_SLOTS
NODE_PHYSICAL_CORES
NODE_LOGICAL_CORES
NODE_SHUTDOWN_COMMAND
```
2. by creating structure templates and referencing the main one in the MACHINE_FEATURES_TEMPLATE variable. This following dictionary keys will be used for searching worker node information:
```
hs06
shutdowntime
jobslots
phys_cores
log_cores
shutdown_command
```
Only leaf values matching the escaped FQDNs of the …

Worker node machine features + Torque client job features

---

vo/params/icecube.pan

Following the documentation (https://grid-voms.desy.de:8443/voms/icecube/configuration/configuration.action), the port used to contact this server should be 15109 (instead of 15106)

Change grid-voms.desy.de port

---

features/htcondor/params.pan
features/htcondor/templ/head.pan
features/htcondor/templ/submit.pan

support for defining SUBMIT REQUIREMENTS which are named rule to allow submission from a submit node. Useful for restricting the usage of one queue (e.g. muticore queue to multicore jobs) and to drain selectively one queue.

support for SUBMIT REQUESTS

---

personality/xrootd/config.pan
personality/xrootd/env.pan

This PR doesn't produce any configuration change by itself, without a new version of ncm-xrootd (https://github.com/quattor/configuration-modules-grid/pull/105) planned for 16.6 but is a requirement for deploying this new version. Because it is a requirement I think **it should be part of 16.4**.
Contributes to https://github.com/quattor/configuration-modules-grid/issues/104

xrootd: define GSI security protocol params by default

---

features/globus/env.pan

- Definition incorrect: breaks the possibility to use standard SASL plugins
Fixes #177.

Globus: remove SASL_PATH env variable definition

---

personality/se_dpm/puppet/puppetconf.pan

Just adding few lines to allow people to choose another puppet module for configuring dpm or to not use the ncm-puppet component for getting the module (for example by using some rpm's containing the modules).
Cheers,
Andrea

more flexibility in using the puppet module for dpm

---

personality/se_dpm/puppet/puppetconf.pan

Requires https://github.com/quattor/template-library-core/pull/131 to be merged first... but would be good to merge at the same time.

DPM: use PKG_VERSION_xxx for testing pkg_compare_version() return value

---

defaults/grid/config.pan

Fix a regression introduced in #7e395505e652eb6491574164cb528e0b718f65e3 preventing the template to compile successfully.
Showstopper for https://github.com/quattor/release/issues/278#issuecomment-270122186.

defaults/grid/config: fix typo introducted in 7e39550

---

personality/se_dpm/config_dmlite.pan
personality/se_dpm/server/config_dmlite.pan

Change the name of the variable to something more explicit. It permit also to avoid issues with local variable name (like 'contents').

Rename variable (issue with local scope naming)

---

features/wlcg/config.pan

Set the HEP_OSlib RPM name for CentOS 7 accordingly to the RPM available in the WLCG repo

Use correct name for HEP_OSlib RPM on EL7

---

personality/cream_ce/monitor.pan

Not tested, but should fix #199.

Allow location of CREAM monitoring configuration file to be changed

---

features/puppet/config.pan
features/puppet/defaults.pan
features/puppet/defaults_4+.pan
features/puppet/defaults_5+.pan

This PR goes with https://github.com/quattor/configuration-modules-core/pull/1201 the components and schema have been updated to be compliant with the most recent versions of puppet. I've just introduced a default.pan template managing the different default values corresponding to different versions.

set default values for different puppet versions

---

personality/se_dpm/puppet/no_pool_accounts.pan
personality/se_dpm/puppet/puppetconf.pan
personality/se_dpm/service_puppet.pan

Changed the templates for configuring DPM using the ncm-puppet component. Now they use the offical dmlite-dpm puppet module rather than the legacy sartiran-dpm. Also some defaults have been changed. Upgrading to this new version of templ is not transparent but as far as I know the only site using these templates, at the moment, is GRIF (which has already upgraded to the new version).

new version using the std dpm puppet modules

---

features/wlcg/config.pan
personality/ui/rpms/config.pan

HEP_OSlibs_SL7 is now named HEP_OSlibs in wlcg centos7 repo.
emi-ui is now named ui in the umd-4 repo (1st release https://twiki.cern.ch/twiki/bin/view/LCG/EL7UIMiddleware)

HEP_OSlibs and ui rpm name changed

---

personality/se_dpm/puppet/forge_modules.pan
personality/se_dpm/puppet/puppetconf.pan
personality/se_dpm/puppet/release_modules.pan

This allows to use the dpm puppet modules released with epel rather than those in forge.
Tested at GRIF LLR (no issues seen so far)

allow use of the dpm puppet modules in the epel release

---

users/edginfo.pan
users/infosys.pan

From EL7 onwards, non-system IDs should be above 1000, the existing values conflict with system managed groups.
Fixes #226.
I believe this is backwards incompatible as ncm-accounts will alter existing groups, which may have interesting side-effects.

users: Fix collisions with system managed groups

---

defaults/grid/config.pan

If max_threads is defined it cannot be used in a boolean context. Being defined is enough as we've introduced validation in the schema to ensure the value is not smaller than the core count.
This is only really needed to fix the tests on other template library repos.

umd-3: Fix max_threads reference

---

features/mysql/server.pan

Fix required to allow the examples to compile successfully (https://github.com/quattor/template-library-grid/pull/246)

features/mysqld: fix syntax error
